// The public API of @depesha/plugin-api. Generated by scripts/plugin-api-snapshot.mjs; do not edit.
// After a deliberate change: npm run plugin-api:update, and a line in plugins/CHANGELOG.md.
// svelte major: 5

import type { Component, Snippet } from "svelte";

export interface ActsOn {
    account_id: string;
    message_id: string;
    folder: string;
    act: Act;
    waiting: boolean;
}

export interface Anchor {
    x: number;
    y: number;
    h?: number;
}

export interface Banner {
    text: string;
    tone?: "info" | "warn" | "good";
    icon?: Component;
    details?: {
        label: string;
        value: string;
    }[];
    detailsTitle?: string;
    actions?: {
        title: string;
        run: () => void;
        primary?: boolean;
    }[];
}

export interface Clock {
    h: number;
    m: number;
}

export interface Command {
    id: string;
    title: () => string;
    hint?: () => string;
    synonyms?: () => string;
    when?: () => boolean;
    run: () => void;
}

export interface ComposeContext {
    readonly draft: ComposeDraft;
    accountEmail(): string;
    accountId(): string;
    accountColor(): string;
    insertText(text: string): void;
    options: {
        at: number | null;
        followupDays: number | null;
        followupSecs: number | null;
        followup: FollowupPlan | null;
        park: boolean | null;
    };
    onAction(action: "park" | "remind", run: () => void): () => void;
    send(at?: number | null): void;
}

export interface ComposeDraft {
    from: Addr | null;
    to: Addr[];
    cc: Addr[];
    bcc: Addr[];
    subject: string;
    text: string;
    html?: string | null;
    signature?: string | null;
    format?: BodyFormat;
    in_reply_to: string | null;
    references: string[];
    attachments: AttachmentSource[];
    send_at?: number | null;
    acts_on?: ActsOn | null;
    importance?: Importance;
}

export declare const DEFAULT_WORK_TIME: WorkTime;

export interface FileViewer {
    id: string;
    extensions?: string[];
    mimes?: string[];
    match?: (file: {
        name: string;
        mime: string;
    }) => boolean;
    priority?: number;
    component: Component<any>;
    props?: Record<string, unknown>;
}

export interface FolderInfo {
    account_id: string;
    name: string;
    display_name: string;
    delimiter: string | null;
    role: FolderRole | null;
    selectable: boolean;
    hidden: boolean;
    total: number;
    unread: number;
}

export interface FollowupInfo {
    status: FollowupStatus;
    due: number;
    deadline: number;
    own_deadline: boolean;
    repeat_secs: number;
    expect: string;
    kind: string;
    ended: number | null;
    answered_by: Addr | null;
    answer: number | null;
    reminded: number[];
    sent: number;
    park: string;
    park_folder: string;
    auto_reply: number | null;
}

export interface FollowupPlan {
    deadline_secs: number;
    due_at?: number;
    deadline_at?: number;
    repeat_secs: number;
    expect: string;
    kind: string;
    park?: boolean | null;
    archive?: boolean | null;
}

export interface KeyBinding {
    id: string;
    title: () => string;
    key?: string;
    run: () => void;
    when?: () => boolean;
    where?: "everywhere" | "list";
}

export declare const Keys: Component<KeysProps>;

export interface KeysProps {
    key?: string;
    of?: string;
}

export type Lang = "en" | "ru";

export declare const LaterMenu: Component<LaterMenuProps>;

export interface LaterMenuProps {
    title: string;
    presets: Preset[];
    action: string;
    onPick: (at: number) => void;
}

export interface ListFilter {
    title: () => string;
    options: () => {
        id: string;
        title: string;
    }[];
    current: (list: ListScope) => string;
    select: (list: ListScope, id: string) => void;
    query: (list: ListScope) => Partial<ListQuery>;
}

export interface ListQuery {
    account_id?: string | null;
    folder?: string | null;
    role?: FolderRole | null;
    unread_only?: boolean;
    flagged_only?: boolean;
    keep_ids?: number[];
    bulk?: boolean | null;
    threads?: boolean;
    snoozed_only?: boolean;
    followups_only?: boolean;
    followup_status?: "active" | "closed";
    sort?: SortKey[];
    pins?: Pin[];
    limit?: number;
    offset?: number;
}

export interface ListScope {
    key: string;
    inbox: boolean;
}

export interface MessageAction {
    id: string;
    title: () => string;
    icon?: Component;
    hint?: string;
    when?: (msg: OpenedMessage) => boolean;
    run: (msg: OpenedMessage) => void;
}

export interface MessageRow {
    id: number;
    account_id: string;
    folder: string;
    uid: number;
    message_id: string | null;
    in_reply_to: string | null;
    references: string[];
    subject: string;
    from: Addr | null;
    to: Addr[];
    cc: Addr[];
    reply_to: Addr[];
    date: number;
    size: number;
    flags: Flags;
    keywords?: string[];
    has_attachments: boolean;
    thread: string;
    bulk: boolean;
    thread_count: number;
    thread_date: number;
    thread_senders: Addr[];
    thread_draft: boolean;
    thread_size?: number;
    snoozed_until: number | null;
    followup_due: number | null;
    followup?: FollowupInfo | null;
    marks?: Mark[];
    my_answer?: number | null;
    outgoing?: Outgoing | null;
    answer_came?: boolean;
    dmarc?: boolean;
    thread_voices?: Voice[];
    importance?: Importance;
}

export interface Moved {
    account_id: string;
    from: string;
    to: string;
    message_ids: string[];
    unseen?: string[];
    snoozed?: {
        subject: string;
    }[];
}

export interface OpenedMessage {
    row: MessageRow;
    view: MessageView;
    trusted_sender: boolean;
    sender_unverified?: boolean;
}

export interface Placed {
    left: number;
    top: number;
    maxHeight: number;
    below: boolean;
}

export interface Plugin {
    manifest: PluginManifest;
    activate(ctx: PluginContext): void | (() => void);
}

export interface PluginContext {
    readonly id: string;
    lang(): Lang;
    t(text: Text, params?: Record<string, string | number>): string;
    plural(n: number, forms: {
        en: PluralForms;
        ru: PluralForms;
    }): string;
    commands(): Command[];
    keyOf(commandId: string): string | undefined;
    keyTitle(text: string, commandId: string): string;
    editKeys(commandId: string, title: string): void;
    people: {
        find(query: string): {
            name: string;
            email: string;
            emails: string[];
        }[];
        open(email: string): void;
        allMail(email: string): void;
    };
    mail: {
        opened(): OpenedMessage | null;
        selection(): number[];
        accounts(): {
            id: string;
            email: string;
            display_name: string;
            label?: string;
            waiting?: Waiting;
        }[];
        folders(): FolderInfo[];
        perform(text: string | ((moved: Moved[]) => string), ids: number[], run: (ids: number[]) => Promise<Moved[]>, failText: string): Promise<void>;
        offerUndo(text: string, run: () => Promise<void>): void;
        reload(): void;
        scheduleReload(): void;
        showView(id: string): void;
        viewing(id: string): boolean;
        compose(): void;
        reply(all: boolean): void;
        open(id: number, view?: string): Promise<void>;
        main(): boolean;
    };
    backend<T>(command: string, args?: Record<string, unknown>): Promise<T>;
    onBackend(event: string, run: (payload: unknown) => void): void;
    openLink(url: string): void;
    toast(text: string, opts?: {
        error?: boolean;
        action?: {
            label: string;
            run: () => void;
        };
        ms?: number;
    }): void;
    fail(e: unknown, prefix?: string): void;
    anchor(): Anchor;
    workTime(): WorkTime;
    settings: {
        get<T>(key: string, fallback: T): T;
        set(key: string, value: unknown): void;
    };
    ui: {
        command(c: Command): void;
        keybinding(b: KeyBinding): void;
        keybinding(key: string, run: () => void, when?: () => boolean): void;
        readerToolbar(r: Rendered): void;
        bulkToolbar(r: Rendered): void;
        readerHeader(r: Rendered): void;
        messageAction(a: MessageAction): void;
        rowAction(a: RowAction): void;
        banner(provider: (msg: OpenedMessage) => Banner | null): void;
        rowTag(provider: (row: MessageRow) => RowTag | null): void;
        view(v: View): void;
        listFilter(f: ListFilter): void;
        composeControl(c: {
            component: Component<{
                compose: ComposeContext;
                ctx: PluginContext;
            }>;
            props: {
                ctx: PluginContext;
            };
            order?: number;
            slot?: "send" | "footer" | "line" | "from";
        }): void;
        sendCheck(check: (draft: ComposeDraft, accountEmail: string) => string[]): void;
        settingsSection(s: {
            title: () => string;
            component: Component<{
                ctx: PluginContext;
            }>;
            props: {
                ctx: PluginContext;
            };
            page?: string;
        }): void;
        overlay(r: Rendered): void;
        fileViewer(v: FileViewer): void;
    };
}

export interface PluginManifest {
    id: string;
    name: Text;
    description: Text;
    defaultOff?: boolean;
}

export interface PluralForms {
    one?: string;
    few?: string;
    many?: string;
    other: string;
}

export declare const Popover: Component<PopoverProps, object, "open">;

export interface PopoverProps {
    open: boolean;
    align?: "left" | "right";
    matchWidth?: boolean;
    role?: "menu" | "listbox";
    children: Snippet;
}

export interface Preset {
    label: string;
    at: number;
    hint: string;
}

export interface Rendered {
    component: Component<any>;
    props?: Record<string, unknown>;
}

export interface RowAction {
    id: string;
    title: () => string;
    icon?: Component;
    hint?: string;
    command?: string;
    when?: (ids: number[], rows: MessageRow[]) => boolean;
    run?: (ids: number[], at?: Anchor) => void;
    menu?: Rendered;
}

export interface RowTag {
    icon?: Component;
    text: string;
    note?: {
        text: string;
        icon?: Component;
    };
    title?: string;
    alert?: boolean;
    good?: boolean;
    info?: boolean;
}

export declare const Select: Component<SelectProps<any>, object, "value">;

export interface SelectProps<T> {
    value: T;
    options: {
        value: T;
        label: string;
    }[];
    onchange?: (value: T) => void;
    title?: string;
    label?: string;
    disabled?: boolean;
    class?: string;
}

export interface Text {
    en: string;
    ru: string;
}

export interface View {
    id: string;
    title: () => string;
    icon: Component;
    count: () => number;
    query: () => ListQuery;
    showRecipients?: boolean;
    empty: () => string;
    tabs?: ViewTabs;
    shown?: () => boolean;
}

export interface ViewTabs {
    options: () => {
        id: string;
        title: string;
        count?: number;
    }[];
    current: () => string;
    select: (id: string) => void;
}

export interface ViewedFile {
    name: string;
    mime: string;
    size: number;
    bytes(): Promise<ArrayBuffer>;
    text(): Promise<{
        text: string;
        cut: boolean;
    }>;
    openLink(href: string): void;
    fail(e: unknown): void;
}

export interface Waiting {
    park: boolean;
    folder: string;
    stop_to_archive: boolean;
}

export interface WhenExtras {
    none: boolean;
    noneLabel: string;
    setupLabel: string;
}

export interface WhenMenuRequest {
    anchor: Anchor;
    extras: WhenExtras;
    texts: {
        placeholder: string;
        title: string;
        pick: string;
    };
    notBefore?: number;
    onpick: (at: number) => void;
    onnone: () => void;
    onsetup: () => void;
    onclose: () => void;
}

export interface WorkTime {
    day: Clock;
    evening: Clock;
    days: number[];
}

export declare function addrName(a: Addr | null | undefined): string;

export declare function closeWhenMenu(): void;

export declare function formatClock(c: Clock): string;

export declare function fromLocalInput(value: string): number | null;

export declare function listDate(unix: number, now?: Date): string;

export declare function matches(label: string, query: string): boolean;

export declare function openWhenMenu(request: WhenMenuRequest): void;

export declare function parseClock(text: string): Clock | null;

export declare function placeMenu(anchor: Anchor, size: Size, win: Size): Placed;

export declare function placeSide(parent: Box, size: Size, win: Size): { left: number; top: number; maxHeight: number; };

export declare function provideWhenMenu(on: boolean): void;

export declare function roleLabel(role: FolderRole): string;

export declare function sendLaterPresets(now?: Date): Preset[];

export declare function toLocalInput(unix: number): string;

export declare function when(unix: number, now?: Date): string;

export declare function whenMenuAvailable(): boolean;

export declare function whenMenuRequest(): WhenMenuRequest | null;

type Act = "reply" | "reply_all" | "forward";

interface Addr {
    name: string | null;
    email: string;
}

interface AttachmentInfo {
    index: number;
    name: string;
    mime: string;
    size: number;
    content_id: string | null;
    inline: boolean;
}

type AttachmentSource = {
    kind: "file";
    path: string;
    name: string;
    size: number;
} | {
    kind: "message";
    id: number;
    index: number;
    name: string;
    size: number;
};

type BodyFormat = "plain" | "html" | "markdown";

type BodyView = "text" | "html" | "markdown";

interface Box {
    left: number;
    top: number;
    right: number;
    bottom: number;
}

interface Flags {
    seen: boolean;
    answered: boolean;
    flagged: boolean;
    draft: boolean;
    deleted: boolean;
    forwarded?: boolean;
    answered_all?: boolean;
}

type FolderRole = "inbox" | "sent" | "drafts" | "trash" | "junk" | "archive" | "snoozed";

type FollowupStatus = "waiting" | "answered" | "closed";

type Importance = "low" | "normal" | "high";

interface Mark {
    act: Act;
    at: number | null;
}

interface MessageView {
    summary: Summary;
    text: string | null;
    html: string | null;
    has_remote_content: boolean;
    authenticated: boolean;
    attachments: AttachmentInfo[];
    send_at?: number | null;
    format?: BodyFormat | null;
    acts_on?: ActsOn | null;
    markdown?: string | null;
    views?: BodyView[];
}

interface Outgoing {
    act: Act;
    at: number;
    park: boolean;
    scheduled: boolean;
}

interface Pin {
    id: number;
    unread: boolean;
    flagged: boolean;
}

interface Size {
    w: number;
    h: number;
}

type SortField = "date" | "unread" | "flagged" | "people" | "sender" | "subject" | "size" | "attachments" | "relevance";

interface SortKey {
    by: SortField;
    desc: boolean;
}

interface Summary {
    message_id: string | null;
    in_reply_to: string | null;
    references: string[];
    subject: string;
    from: Addr | null;
    to: Addr[];
    cc: Addr[];
    reply_to: Addr[];
    date: number | null;
    has_attachments: boolean;
    bulk: boolean;
    unsubscribe: Unsubscribe | null;
    importance?: Importance;
}

interface Unsubscribe {
    one_click: string | null;
    http: string | null;
    mailto: string | null;
}

interface Voice {
    from: Addr;
    dmarc: boolean;
    id: number;
}
