export const S = {
  name: { en: "Snooze", ru: "Отложить" },
  about: {
    en: "Hide a message until a chosen time; it comes back to the inbox unread.",
    ru: "Убрать письмо до нужного времени; оно вернётся во входящие непрочитанным.",
  },
  action: { en: "Snooze", ru: "Отложить" },
  hint: { en: "Snooze: back in the inbox later", ru: "Отложить: вернётся во входящие позже" },
  menuTitle: { en: "Back to the inbox", ru: "Вернуть во входящие" },
  view: { en: "Snoozed", ru: "Отложенные" },
  empty: {
    en: "No snoozed mail. Press h on a message to bring it back later.",
    ru: "Отложенных писем нет. Нажмите h на письме, чтобы оно вернулось позже.",
  },
  done: { en: "Snoozed: back {when}", ru: "Отложено: вернётся {when}" },
  failed: { en: "Could not snooze", ru: "Не удалось отложить" },
  command: { en: "Snooze: {when}", ru: "Отложить: {when}" },
  release: { en: "Bring back now", ru: "Вернуть сейчас" },
  releaseHint: { en: "Bring back now: to the folder it was snoozed from", ru: "Вернуть сейчас: в папку, откуда отложено" },
  released: { en: "Brought back to “{folder}”: {what}", ru: "Возвращено во «{folder}»: {what}" },
  releasedMany: { en: { one: "{n} message", other: "{n} messages" }, ru: { one: "{n} письмо", few: "{n} письма", other: "{n} писем" } },
  noSubject: { en: "(no subject)", ru: "(без темы)" },
  releaseFailed: { en: "Could not bring back", ru: "Не удалось вернуть" },
  tag: { en: "Returns to the inbox", ru: "Вернётся во входящие" },
  banner: { en: "Snoozed: back in the inbox {when}.", ru: "Отложено: вернётся во входящие {when}." },
};
