export const S = {
  name: { en: "Snooze", ru: "Отложить" },
  about: {
    en: "Hide a message until a chosen time; it comes back to the inbox unread.",
    ru: "Убрать письмо до нужного времени; оно вернётся во входящие непрочитанным.",
  },
  action: { en: "Snooze", ru: "Отложить" },
  hint: { en: "Snooze: back in the inbox later", ru: "Отложить: вернётся во входящие позже" },
  menuTitle: { en: "Back to the inbox", ru: "Вернуть во входящие" },
  evening: { en: "This evening", ru: "Вечером" },
  tomorrow: { en: "Tomorrow", ru: "Завтра" },
  weekend: { en: "This weekend", ru: "Эти выходные" },
  nextWeek: { en: "Next week", ru: "Следующая неделя" },
  nextMonth: { en: "Next month", ru: "Следующий месяц" },
  days: { en: "Working days", ru: "Рабочие дни" },
  custom: { en: "Pick date and time…", ru: "Выбрать дату и время…" },
  passed: { en: "already passed", ru: "уже наступил" },
  noWorkDays: { en: "no working days", ru: "нет рабочих дней" },
  noneChosen: { en: "none chosen", ru: "не выбраны" },
  fromYou: { en: "as you typed", ru: "по вашему вводу" },
  placeholder: { en: "When? Fri 9:00 · tomorrow 18 · in 3 days · 15 Oct", ru: "Когда? пт 9:00 · завтра 18 · через 3 дня · 15 окт" },
  notUnderstood: { en: "Not understood. Examples: Fri 9:00 · tomorrow 18 · in 3 days · 15 Oct · in an hour", ru: "Не понял. Примеры: пт 9:00 · завтра 18 · через 3 дня · 15 окт · через час" },
  timePassed: { en: "That time has already passed", ru: "Это время уже прошло" },
  dayTimes: { en: "Day starts {day} · evening {evening}", ru: "День с {day} · вечер с {evening}" },
  inSettings: { en: "set in Settings", ru: "меняется в настройках" },
  pickTitle: { en: "Pick date and time", ru: "Выбрать дату и время" },
  time: { en: "Time", ru: "Время" },
  timeKeys: { en: "↑↓ ±15 min · ⇧ ±1 h", ru: "↑↓ ±15 мин · ⇧ ±1 ч" },
  timeFormat: { en: "Time like 9:30", ru: "Время: например 9:30" },
  cancel: { en: "Cancel", ru: "Отмена" },
  prevMonth: { en: "Previous month", ru: "Предыдущий месяц" },
  nextMonthStep: { en: "Next month", ru: "Следующий месяц" },
  calKeys: {
    en: "←→ day · ↑↓ week · PgUp/PgDn month · Shift+PgUp/PgDn year · Tab time · Enter snooze · Esc back",
    ru: "←→ день · ↑↓ неделя · PgUp/PgDn месяц · Shift+PgUp/PgDn год · Tab к времени · Enter отложить · Esc назад",
  },
  view: { en: "Snoozed", ru: "Отложенные" },
  empty: {
    en: "No snoozed mail. Press h on a message to bring it back later.",
    ru: "Отложенных писем нет. Нажмите h на письме, чтобы оно вернулось позже.",
  },
  done: { en: "Snoozed until {when}", ru: "Отложено до {when}" },
  failed: { en: "Could not snooze", ru: "Не удалось отложить" },
  command: { en: "Snooze: {when}", ru: "Отложить: {when}" },
  release: { en: "Bring back now", ru: "Вернуть сейчас" },
  releaseHint: { en: "Bring back now: to the folder it was snoozed from", ru: "Вернуть сейчас: в папку, откуда отложено" },
  released: { en: "Brought back to “{folder}”: {what}", ru: "Возвращено во «{folder}»: {what}" },
  releasedMany: { en: { one: "{n} message", other: "{n} messages" }, ru: { one: "{n} письмо", few: "{n} письма", other: "{n} писем" } },
  noSubject: { en: "(no subject)", ru: "(без темы)" },
  releaseFailed: { en: "Could not bring back", ru: "Не удалось вернуть" },
  tag: { en: "Returns to the inbox", ru: "Вернётся во входящие" },
  banner: { en: "Snoozed: back in the inbox {when}.", ru: "Отложено: вернётся во входящие {when}." },
};
